#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LogonScreen.Resource", IsApplication=false)]

namespace LogonScreen
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public static int Login = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int Password = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int User = 2131034112;
			
			// aapt resource value: 0x7f050004
			public static int msgPkgInfo = 2131034116;
			
			// aapt resource value: 0x7f050003
			public static int msgText = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int LogonScreenLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int LogonScreenLayoutMaterial = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public static int Antares = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int decodeshort = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int Gallium = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int TaDa = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int Tejat = 2130903044;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
